package com.ssm.entity;

public class FileEntity {
	
	
	
    public FileEntity() {
		super();
	}

	public FileEntity(boolean upFlag) {
		super();
		this.upFlag = upFlag;
	}

    
	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fileupload.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fileupload.up_name
     *
     * @mbg.generated
     */
    private String upName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fileupload.up_date
     *
     * @mbg.generated
     */
    private String upDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fileupload.up_path
     *
     * @mbg.generated
     */
    private String upPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fileupload.up_time
     *
     * @mbg.generated
     */
    private String upTime;
    
    //临时变量
    private boolean upFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fileupload.id
     *
     * @return the value of t_fileupload.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fileupload.id
     *
     * @param id the value for t_fileupload.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fileupload.up_name
     *
     * @return the value of t_fileupload.up_name
     *
     * @mbg.generated
     */
    public String getUpName() {
        return upName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fileupload.up_name
     *
     * @param upName the value for t_fileupload.up_name
     *
     * @mbg.generated
     */
    public void setUpName(String upName) {
        this.upName = upName == null ? null : upName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fileupload.up_date
     *
     * @return the value of t_fileupload.up_date
     *
     * @mbg.generated
     */
    public String getUpDate() {
        return upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fileupload.up_date
     *
     * @param upDate the value for t_fileupload.up_date
     *
     * @mbg.generated
     */
    public void setUpDate(String upDate) {
        this.upDate = upDate == null ? null : upDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fileupload.up_path
     *
     * @return the value of t_fileupload.up_path
     *
     * @mbg.generated
     */
    public String getUpPath() {
        return upPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fileupload.up_path
     *
     * @param upPath the value for t_fileupload.up_path
     *
     * @mbg.generated
     */
    public void setUpPath(String upPath) {
        this.upPath = upPath == null ? null : upPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fileupload.up_time
     *
     * @return the value of t_fileupload.up_time
     *
     * @mbg.generated
     */
    public String getUpTime() {
        return upTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fileupload.up_time
     *
     * @param upTime the value for t_fileupload.up_time
     *
     * @mbg.generated
     */
    public void setUpTime(String upTime) {
        this.upTime = upTime == null ? null : upTime.trim();
    }

	public boolean isUpFlag() {
		return upFlag;
	}

	public void setUpFlag(boolean upFlag) {
		this.upFlag = upFlag;
	}

    
}