package com.ssm.dao;

import com.ssm.entity.FileEntity;
import com.ssm.entity.FileEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FileEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fileupload
     *
     * @mbg.generated
     */
    long countByExample(FileEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fileupload
     *
     * @mbg.generated
     */
    int deleteByExample(FileEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fileupload
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fileupload
     *
     * @mbg.generated
     */
    int insert(FileEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fileupload
     *
     * @mbg.generated
     */
    int insertSelective(FileEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fileupload
     *
     * @mbg.generated
     */
    List<FileEntity> selectByExample(FileEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fileupload
     *
     * @mbg.generated
     */
    FileEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fileupload
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FileEntity record, @Param("example") FileEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fileupload
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FileEntity record, @Param("example") FileEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fileupload
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FileEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fileupload
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FileEntity record);
}